### ISSUE TITLE
前端圈-酷狗专场学习心得

### ISSUE THREAD

**Issue by Yeahax** [Yeahax/blog#2]
第一次参加这种技术会议，满满的干货啊，感谢前端圈(_^__^_)！酷狗对这一次活动也是挺重视的，为酷狗点个赞！

**分享一：繁星网的前端性能优化之路**

“性能优化”这一个词对于我们并不陌生，业界对于网站性能优化也有好多好的知识，例如“雅虎34条”，这一次白伟民大神向我们讲解了从客户端、服务端、网络这三个方面对繁星网的优化，使用户体验变得更好。
###### 服务端
- 接口按需请求
- 接口走CDN
- 静态资源走CDN
###### 网络
- 背景图合并
- js/css文件选择性合并、压缩
- 图片按需加载
- 合理使用静态资源域名
###### 客户端
- js文件尾部引入，按需加载
- 非核心模块异步
- 合理分配域名
- 一些flash可以使用canvas代替（移动端可以全用canvas）

**分享二：前端页面加载性能数据之采集和分析**

> 当对网站做了性能优化之后，网站比之前“快”了多少呢？

这时候就要进行性能数据采集和分析了，这样才能比较知道通过之前的性能优化，网站比之前“快”了多少。

**分享三：酷狗内嵌前端页面发展史**

因为酷狗的内核是IE，老师把他开发过程中遇到的问题分享给我们，例如：

``` html
<a href="javascript:void(0)"></a>
```

``` css
a{
    display: block;
    width: 10px;
    height: 10px;
    background: url(../images/a.png) no-repeat;
}
```

如果a标签的背景图片还没加载完成时，用户就点击了，这时背景图片就不会再加载，为了解决这个问题，我们应该这样写：

``` html
<a href="javascript:void(0)" onclick="return false"></a>
```

这样就能解决这个问题了。

最后要说的是，酷狗的3d赛车游戏体验机真是吊炸天，好想上去玩一下！>_<
先写到这里，具体的内容可以等PPT出来，再一次感谢前端圈提供了这一次机会，以后一定会继续参加这一种活动。
